#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : libkdegames
Version  : 18.08.0
Release  : 1
URL      : https://download.kde.org/stable/applications/18.08.0/src/libkdegames-18.08.0.tar.xz
Source0  : https://download.kde.org/stable/applications/18.08.0/src/libkdegames-18.08.0.tar.xz
Source99 : https://download.kde.org/stable/applications/18.08.0/src/libkdegames-18.08.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GFDL-1.2 GPL-2.0 MIT
Requires: libkdegames-lib
Requires: libkdegames-data
Requires: libkdegames-license
Requires: libkdegames-locales
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : kdnssd-dev
BuildRequires : kglobalaccel-dev
BuildRequires : libsndfile-dev
BuildRequires : libsndfile-extras
BuildRequires : openal-soft-dev
BuildRequires : qtbase-dev qtbase-extras mesa-dev

%description
This directory contains the library for the kdegames package.
It is a collection of functions used by some games or which
are useful for other games.

%package data
Summary: data components for the libkdegames package.
Group: Data

%description data
data components for the libkdegames package.


%package dev
Summary: dev components for the libkdegames package.
Group: Development
Requires: libkdegames-lib
Requires: libkdegames-data
Provides: libkdegames-devel

%description dev
dev components for the libkdegames package.


%package lib
Summary: lib components for the libkdegames package.
Group: Libraries
Requires: libkdegames-data
Requires: libkdegames-license

%description lib
lib components for the libkdegames package.


%package license
Summary: license components for the libkdegames package.
Group: Default

%description license
license components for the libkdegames package.


%package locales
Summary: locales components for the libkdegames package.
Group: Default

%description locales
locales components for the libkdegames package.


%prep
%setup -q -n libkdegames-18.08.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535222285
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
pushd clr-build ; make test ||: ; popd

%install
export SOURCE_DATE_EPOCH=1535222285
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libkdegames
cp COPYING %{buildroot}/usr/share/doc/libkdegames/COPYING
cp COPYING.DOC %{buildroot}/usr/share/doc/libkdegames/COPYING.DOC
cp carddecks/svg-konqi-modern/COPYRIGHT %{buildroot}/usr/share/doc/libkdegames/carddecks_svg-konqi-modern_COPYRIGHT
cp cmake/modules/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/doc/libkdegames/cmake_modules_COPYING-CMAKE-SCRIPTS
pushd clr-build
%make_install
popd
%find_lang libkdegames5

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/carddecks/svg-ancient-egyptians/11.png
/usr/share/carddecks/svg-ancient-egyptians/Ancient_Egyptians.svgz
/usr/share/carddecks/svg-ancient-egyptians/index.desktop
/usr/share/carddecks/svg-dondorf/11.png
/usr/share/carddecks/svg-dondorf/dondorf.svgz
/usr/share/carddecks/svg-dondorf/index.desktop
/usr/share/carddecks/svg-future/11.png
/usr/share/carddecks/svg-future/future.svgz
/usr/share/carddecks/svg-future/index.desktop
/usr/share/carddecks/svg-gm-paris/11.png
/usr/share/carddecks/svg-gm-paris/index.desktop
/usr/share/carddecks/svg-gm-paris/paris.svgz
/usr/share/carddecks/svg-jolly-royal/11.png
/usr/share/carddecks/svg-jolly-royal/index.desktop
/usr/share/carddecks/svg-jolly-royal/jolly-royal.svgz
/usr/share/carddecks/svg-konqi-modern/11.png
/usr/share/carddecks/svg-konqi-modern/index.desktop
/usr/share/carddecks/svg-konqi-modern/konqi.svgz
/usr/share/carddecks/svg-nicu-ornamental/11.png
/usr/share/carddecks/svg-nicu-ornamental/AUTHORS
/usr/share/carddecks/svg-nicu-ornamental/COPYING
/usr/share/carddecks/svg-nicu-ornamental/index.desktop
/usr/share/carddecks/svg-nicu-ornamental/ornamental.svgz
/usr/share/carddecks/svg-nicu-white/11.png
/usr/share/carddecks/svg-nicu-white/AUTHORS
/usr/share/carddecks/svg-nicu-white/COPYING
/usr/share/carddecks/svg-nicu-white/index.desktop
/usr/share/carddecks/svg-nicu-white/white.svgz
/usr/share/carddecks/svg-oxygen-air/11.png
/usr/share/carddecks/svg-oxygen-air/index.desktop
/usr/share/carddecks/svg-oxygen-air/oxygen-air.svgz
/usr/share/carddecks/svg-oxygen-white/11.png
/usr/share/carddecks/svg-oxygen-white/index.desktop
/usr/share/carddecks/svg-oxygen-white/oxygen-white.svgz
/usr/share/carddecks/svg-oxygen/11.png
/usr/share/carddecks/svg-oxygen/index.desktop
/usr/share/carddecks/svg-oxygen/oxygen.svgz
/usr/share/carddecks/svg-penguins/11.png
/usr/share/carddecks/svg-penguins/COPYRIGHT
/usr/share/carddecks/svg-penguins/index.desktop
/usr/share/carddecks/svg-penguins/penguins.svgz
/usr/share/carddecks/svg-standard/11.png
/usr/share/carddecks/svg-standard/index.desktop
/usr/share/carddecks/svg-standard/standard.svgz
/usr/share/carddecks/svg-tigullio-international/index.desktop
/usr/share/carddecks/svg-tigullio-international/queen-of-hearts.png
/usr/share/carddecks/svg-tigullio-international/tigullio-international.svgz
/usr/share/carddecks/svg-xskat-french/11.png
/usr/share/carddecks/svg-xskat-french/COPYRIGHT
/usr/share/carddecks/svg-xskat-french/french.svgz
/usr/share/carddecks/svg-xskat-french/index.desktop
/usr/share/carddecks/svg-xskat-german/11.png
/usr/share/carddecks/svg-xskat-german/COPYRIGHT
/usr/share/carddecks/svg-xskat-german/german.svgz
/usr/share/carddecks/svg-xskat-german/index.desktop
/usr/share/kconf_update/kgthemeprovider-migration.upd

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/KF5KDEGames/KDE/KExtHighscore
/usr/include/KF5/KF5KDEGames/KDE/KGameClock
/usr/include/KF5/KF5KDEGames/KDE/KGamePopupItem
/usr/include/KF5/KF5KDEGames/KDE/KGameRenderedItem
/usr/include/KF5/KF5KDEGames/KDE/KGameRenderedObjectItem
/usr/include/KF5/KF5KDEGames/KDE/KGameRenderer
/usr/include/KF5/KF5KDEGames/KDE/KGameRendererClient
/usr/include/KF5/KF5KDEGames/KDE/KHighscore
/usr/include/KF5/KF5KDEGames/KDE/KScoreDialog
/usr/include/KF5/KF5KDEGames/KDE/KStandardGameAction
/usr/include/KF5/KF5KDEGames/KDE/KgAudioScene
/usr/include/KF5/KF5KDEGames/KDE/KgDeclarativeView
/usr/include/KF5/KF5KDEGames/KDE/KgDifficulty
/usr/include/KF5/KF5KDEGames/KDE/KgSound
/usr/include/KF5/KF5KDEGames/KDE/KgTheme
/usr/include/KF5/KF5KDEGames/KDE/KgThemeProvider
/usr/include/KF5/KF5KDEGames/KDE/KgThemeSelector
/usr/include/KF5/KF5KDEGames/highscore/khighscore.h
/usr/include/KF5/KF5KDEGames/highscore/kscoredialog.h
/usr/include/KF5/KF5KDEGames/kdegames_version.h
/usr/include/KF5/KF5KDEGames/kgameclock.h
/usr/include/KF5/KF5KDEGames/kgamepopupitem.h
/usr/include/KF5/KF5KDEGames/kgamerendereditem.h
/usr/include/KF5/KF5KDEGames/kgamerenderedobjectitem.h
/usr/include/KF5/KF5KDEGames/kgamerenderer.h
/usr/include/KF5/KF5KDEGames/kgamerendererclient.h
/usr/include/KF5/KF5KDEGames/kgaudioscene.h
/usr/include/KF5/KF5KDEGames/kgdeclarativeview.h
/usr/include/KF5/KF5KDEGames/kgdifficulty.h
/usr/include/KF5/KF5KDEGames/kgsound.h
/usr/include/KF5/KF5KDEGames/kgtheme.h
/usr/include/KF5/KF5KDEGames/kgthemeprovider.h
/usr/include/KF5/KF5KDEGames/kgthemeselector.h
/usr/include/KF5/KF5KDEGames/kstandardgameaction.h
/usr/include/KF5/KF5KDEGames/libkdegames_capabilities.h
/usr/include/KF5/KF5KDEGames/libkdegames_export.h
/usr/include/KF5/KF5KDEGames/libkdegamesprivate/kchatbase.h
/usr/include/KF5/KF5KDEGames/libkdegamesprivate/kchatbaseitemdelegate.h
/usr/include/KF5/KF5KDEGames/libkdegamesprivate/kchatbasemodel.h
/usr/include/KF5/KF5KDEGames/libkdegamesprivate/kgame/kgame.h
/usr/include/KF5/KF5KDEGames/libkdegamesprivate/kgame/kgamechat.h
/usr/include/KF5/KF5KDEGames/libkdegamesprivate/kgame/kgameerror.h
/usr/include/KF5/KF5KDEGames/libkdegamesprivate/kgame/kgameio.h
/usr/include/KF5/KF5KDEGames/libkdegamesprivate/kgame/kgamemessage.h
/usr/include/KF5/KF5KDEGames/libkdegamesprivate/kgame/kgamenetwork.h
/usr/include/KF5/KF5KDEGames/libkdegamesprivate/kgame/kgameproperty.h
/usr/include/KF5/KF5KDEGames/libkdegamesprivate/kgame/kgamepropertyhandler.h
/usr/include/KF5/KF5KDEGames/libkdegamesprivate/kgame/kgamesequence.h
/usr/include/KF5/KF5KDEGames/libkdegamesprivate/kgame/kgameversion.h
/usr/include/KF5/KF5KDEGames/libkdegamesprivate/kgame/kmessageclient.h
/usr/include/KF5/KF5KDEGames/libkdegamesprivate/kgame/kmessageio.h
/usr/include/KF5/KF5KDEGames/libkdegamesprivate/kgame/kmessageserver.h
/usr/include/KF5/KF5KDEGames/libkdegamesprivate/kgame/kplayer.h
/usr/include/KF5/KF5KDEGames/libkdegamesprivate/kgamecanvas.h
/usr/include/KF5/KF5KDEGames/libkdegamesprivate/kgamedifficulty.h
/usr/include/KF5/KF5KDEGames/libkdegamesprivate/kgamesvgdocument.h
/usr/include/KF5/KF5KDEGames/libkdegamesprivate/kgametheme.h
/usr/include/KF5/KF5KDEGames/libkdegamesprivate/kgamethemeselector.h
/usr/include/KF5/KF5KDEGames/libkdegamesprivate/libkdegamesprivate_export.h
/usr/lib64/cmake/KF5KDEGames/KF5KDEGamesConfig.cmake
/usr/lib64/cmake/KF5KDEGames/KF5KDEGamesConfigVersion.cmake
/usr/lib64/cmake/KF5KDEGames/KF5KDEGamesLibraryDepends-relwithdebinfo.cmake
/usr/lib64/cmake/KF5KDEGames/KF5KDEGamesLibraryDepends.cmake
/usr/lib64/libKF5KDEGames.so
/usr/lib64/libKF5KDEGamesPrivate.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5KDEGames.so.7
/usr/lib64/libKF5KDEGames.so.7.0.0
/usr/lib64/libKF5KDEGamesPrivate.so.1
/usr/lib64/libKF5KDEGamesPrivate.so.1.0.0
/usr/lib64/qt5/qml/org/kde/games/core/KgItem.qml
/usr/lib64/qt5/qml/org/kde/games/core/libcorebindingsplugin.so
/usr/lib64/qt5/qml/org/kde/games/core/qmldir

%files license
%defattr(-,root,root,-)
/usr/share/doc/libkdegames/COPYING
/usr/share/doc/libkdegames/COPYING.DOC
/usr/share/doc/libkdegames/carddecks_svg-konqi-modern_COPYRIGHT
/usr/share/doc/libkdegames/cmake_modules_COPYING-CMAKE-SCRIPTS

%files locales -f libkdegames5.lang
%defattr(-,root,root,-)

